### ISSUE TITLE
Integrate make-frame-stencil (makeDeltaSpan) and makeDeltaFrame

### ISSUE THREAD

**Issue by uliska** [openlilylib/analysis#5]
It is unacceptable to have these more or less redundant functions side-by-side.

The solution is:

* have *one* function `make-frame-stencil`
* Draw the border like in `makeDeltaFrame`
* Only draw the inner polygon if color is not `##f'`

This will also make it easier to have the border grow *outwards* and (maybe) to have the inner polygon *not* rounded if there is a border.

**Comment by KlausBlum** [comment]
Done. New branch "integrate-MakeDeltaFrame" is ready for revision. 

I could not completely remove the double execution of calculations, because the inner polygon needs a different order (Points must be given in clockwise order - TODO: Test if this is really necessary).
At least, calculations are only executed if a polygon will be drawn. 

Now it is possible to have "empty" borders without inner polygon. 
HOWEVER, `border-radius` > 0 will only lead to usable results if there is no border (i.e. only inner polygon).
Therefore I would recommend to set the default value to zero. This also prevents the problems with broken frames or when working with `open-on-top` / `open-on-bottom`. 

Okay... I'm open to opinions and suggestions.

**Comment by KlausBlum** [comment]
Update: No need to stick to clockwise order. With the lastest commit, all redundant code is removed.

**Comment by KlausBlum** [comment]
Another update: With the latest commits, it's again possible to have `border-radius` > 0. 
`ly:round-filled-polygon` has an optional parameter `extroversion` that prevents the ugly distortions when set to zero. 
Nevertheless, I'd still recommend to have zero as default value.

Any thoughts?

**Comment by KlausBlum** [comment]
Merged 21.06.2020
